### ISSUE TITLE
Creating a menu for the dropdown in the mobile version.

### ISSUE THREAD

**Issue by jpdf00** [george-shammar/Online-Store#2]
- Suggesting the creation of a toggle menu on the hamburger icon for the mobile version of the main page.

**Comment by aliciapaz** [comment]
Congratulations on your project George 👍🏽 
Everything looks nice.
I suggest you take a look at Ismael's repo to see how the toggle menu is done in the mobile version: https://github.com/ixboy/client-s_website

**Comment by george-shammar** [comment]
Okay. I will. Thanks.
